# Indexing

# 1d array indexing

In [3]:
import numpy as np
var=np.array([1,2,3,4,5])
print(var)
print()
#to get first element of array
print(var[0])
#to get second element of array
print(var[1])
#to get 3rd and 4th element by summing them
print(var[2]+var[3])

[1 2 3 4 5]

1
2
7


# 2d array indexing

In [9]:
import numpy as np
var1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#to find 2,7,9,10,5
print(var1[0,1])
print(var1[1,1])
print(var1[1,3])
print(var1[1,4])
print(var1[0,4])

2
7
9
10
5


# 3d array indexing

In [10]:
import numpy as np
var2=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

#to print values of 3,4,5,6,7,10,11,12,14,15,17,18,20
print(var2[0,0,2])
print(var2[0,0,3])
print(var2[0,0,4])
print(var2[0,1,0])
print(var2[0,1,1])
print(var2[0,1,4])
print(var2[1,0,0])
print(var2[1,0,1])
print(var2[1,0,2])
print(var2[1,0,3])
print(var2[1,0,4])
print(var2[1,1,1])
print(var2[1,1,2])
print(var2[1,1,4])

3
4
5
6
7
10
11
12
13
14
15
17
18
20


# negative indexing

In [13]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("last element :",arr[1,-1],arr[0,-1])
#to print 3 and 8 using -ve indexing
print(arr[0,-3],arr[1,-3])


last element : 10 5
3 8


# Slicing

# 1d array slicing

In [15]:
var=np.array([1,2,3,4,5,6,7])
print(var[1:5])
#result includes start
print(var[4:])
#result includes end
print(var[:4])
#negative indexing
print(var[-3:-1])
#step
print(var[1:5:2])
print(var[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


# 2d array slicing

In [22]:
var1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(var1[0,1:4])
print(var1[0,1:])
print(var1[1,2:4])
print(var1[1,1:])
print(var1[0:2,1])
print(var1[0:3,2])

[2 3 4]
[2 3 4 5]
[8 9]
[ 7  8  9 10]
[2 7]
[3 8]


# revision for indexing and slicing

In [26]:
        #for indexing
#1d numpy array
var=np.array([9,8,7,6])
print(var[1])
print(var[-3])
print()
#2d numpy array
var1=np.array([[9,8,7],[4,5,6]])
print(var1[0,1])
print(var1[0,2])
print()
#for 3d numpy array
var2=np.array([[[9,8,7],[4,5,6]]])
print(var2.ndim)
#to get 7,5
print(var2[0,0,2])
print(var2[0,1,1])

8
8

8
7

3
7
5


In [28]:
     #for slicing
#for 1d array
var=np.array([1,2,3,4,5,6])
print(var)
print()
print(var[1:5])
print(var[1:])
print(var[:5])
#step
print(var[::2])
print(var[1:5:2])
#for 2d array
var1=np.array([[1,2,3,4,5],[9,8,7,6,5],[10,11,12,13,14]])
print(var1)
print()
#to print 8 7 6 5
#to print 10 11 12 13 14
print(var1[1,1:5])
print(var1[2,0:])

[1 2 3 4 5 6]

[2 3 4 5]
[2 3 4 5 6]
[1 2 3 4 5]
[1 3 5]
[2 4]
[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [10 11 12 13 14]]

[8 7 6 5]
[10 11 12 13 14]
